"""Pack 7 -- the driver-file emitter.

Four kinds of test live here.

1. GOLDEN emission: fixed inputs -> byte-stable text.  One full-file
   golden for the smallest interesting case, and exact-line goldens for
   the pieces that vary (parquet vs csv, log scale, cross-plot
   x_col/y_col, the [YOURS] blocks).
2. CONTRACT pins: what the emitter refuses, and what it guarantees --
   ASCII output, plain-literal output, a complete fresh file every time
   (W11), never a bare CWD for autosaves, and a NAMED refusal for a
   multi-pane session.
3. EXECUTION smoke: the emitted text is written to disk against a real
   csv AND a real parquet, then RUN in a subprocess with tkinter's
   dialog modules stubbed.  The driver's __main__ guard fires, the
   labeler is constructed for real, and its plot_fn is called against a
   real Agg figure.
4. VALUE round-trip (v2 / V1 MAJOR-1): a known first and last timestamp
   must come back out of the constructed app EXACTLY, parametrized over
   a nanosecond AND a microsecond epoch.  A dtype check cannot tell a
   correct conversion from one that lands in 1970; this can.

No timing assertion appears anywhere in this file.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")

import numpy as np
import pandas as pd
import pytest

import chronotagger
from chronotagger.labeler.utils import vertical_stack_config
from chronotagger.quickstart.driver_export import generate_driver, write_driver

SRC_ROOT = Path(chronotagger.__file__).resolve().parent.parent


# =====================================================================
# fixtures / helpers
# =====================================================================

def _norm(text: str) -> str:
    """Normalised view of generated source.

    Line endings are unified and trailing spaces dropped, so a golden
    cannot flake on invisible whitespace; everything a reader can SEE is
    still compared exactly.
    """
    unified = text.replace("\r\n", "\n").replace("\r", "\n")
    return "\n".join(line.rstrip() for line in unified.split("\n")).strip()


CROSS_LAYOUT = {
    "nrows": 3, "ncols": 2, "hspace": 0.15, "wspace": 0.12,
    "areas": [
        {"key": "panel_1", "row": 0, "col": 0, "role": "time"},
        {"key": "panel_2", "row": 1, "col": 0, "role": "time"},
        {"key": "labels", "row": 2, "col": 0, "role": "labels"},
        {"key": "panel_3", "row": 0, "col": 1, "rowspan": 2,
         "role": "not-time", "x_col": "X", "y_col": "Y"},
    ],
}

CROSS_PLOT_CONFIG = {
    "panel_1": {"role": "time", "y_column": "B", "yscale": "log"},
    "panel_2": {"role": "time", "y_column": "n_linear"},
    # The designer really does put a labels entry in plot_config.  The
    # emitter must skip it BY ROLE -- emitting a block for it is what
    # made the old generate_plot_code produce axs['labels'] -> KeyError.
    "labels": {"role": "labels", "x_column": None, "y_column": None},
    "panel_3": {"role": "not-time", "x_column": "X", "y_column": "Y",
                "equal_aspect": True},
}


def _cross_driver(**kw):
    params = dict(
        data_path=r"E:\artemis\peif.parquet",
        fmt="parquet",
        time_column="t_ns",
        time_is_epoch=True,
        time_unit="ns",
        classes=["sheet", "lobe"],
        colors={"sheet": "#d62728", "lobe": "#1f77b4"},
        autosave_folder="./ct_autosave",
        source_name="peif",
        file_name="drive_artemis.py",
    )
    params.update(kw)
    return generate_driver(
        {"layout_spec": CROSS_LAYOUT, "plot_config": CROSS_PLOT_CONFIG},
        **params)


# =====================================================================
# 1 -- GOLDEN: the whole file, for a 2-panel vertical stack over csv
# =====================================================================

GOLDEN_STACK_CSV = '''\
# ============================================================
# [GEN] ChronoTagger driver -- generated by the Quick-Start Wizard.
# [GEN]
# [GEN] Run it with:   python drive_peif.py
# [GEN]
# [GEN] Every line below is either [GEN] -- written from what the
# [GEN] wizard collected -- or [YOURS] -- scaffolding written ONCE for
# [GEN] you to fill in.  The markers are comments for a human reader.
# [GEN] There is NO merge-on-regenerate: re-running the wizard writes a
# [GEN] complete fresh file over this one.  Once you have edited a
# [GEN] [YOURS] block, this file is the product -- keep editing it here
# [GEN] rather than regenerating.
# [GEN]
# [GEN] HAND-EDIT WARNING -- autosave identity.  ChronoTagger names its
# [GEN] autosave after a fingerprint of the frame it was given: the
# [GEN] sorted column names, the first and last index values, and the
# [GEN] row count.  Change what load_dataframe() returns -- drop a
# [GEN] column, filter rows, subset a time range -- and that
# [GEN] fingerprint MOVES, so an autosave written before the edit is no
# [GEN] longer offered for recovery.  Nothing is lost from disk, but it
# [GEN] will not be found automatically.  SOURCE_NAME below is the
# [GEN] stable human-readable identity; the fingerprint is not.
# ============================================================

import pandas as pd                                        # [GEN]

from chronotagger.labeler import TimeIntervalLabeler       # [GEN]


# ---------------- DATA ------------------------------------- [GEN]
# The driver OWNS data loading, so `python this_file.py` is
# self-contained.  ALL columns are read -- including the non-numeric
# ones the wizard cannot plot -- because your own code below may
# well want them.
DATA_PATH = r"C:\\data\\peif.csv"
TIME_COLUMN = "time"


def load_dataframe():
    df = pd.read_csv(DATA_PATH)
    # TIME_COLUMN holds dates/timestamps, so no unit is involved.
    # If yours is really an INTEGER epoch, regenerate it as one
    # (or add unit="s"/"ms"/"us"/"ns" below): a bare call reads
    # integers as NANOSECONDS and relocates the data to 1970.
    df.index = pd.to_datetime(df[TIME_COLUMN])
    df.index.name = "time"
    df = df.drop(columns=[TIME_COLUMN]).sort_index()
    return df


# ---------------- LABEL SCHEMA ----------------------------- [GEN]
# Rename, add or recolour freely -- this list IS the schema the
# labeler opens with.  Intervals already saved under a class you
# delete keep their old name in the session file.
CLASSES = ["UNKNOWN", "label_1", "label_2"]
COLORS = {
    "UNKNOWN": "#4e79a7",
    "label_1": "#f28e2b",
    "label_2": "#e15759",
}


# ---------------- LAYOUT ----------------------------------- [GEN]
# x_col / y_col on a cross-plot area are what let a box drag on
# that panel select rows by DATAFRAME FILTER instead of by
# scanning drawn artists.  Keep them in step with plot_fn below.
LAYOUT = {
    "nrows": 3,
    "ncols": 1,
    "hspace": 0.15,
    "wspace": 0.12,
    "areas": [
        {"key": "panel_1", "row": 0, "col": 0, "role": "time"},
        {"key": "panel_2", "row": 1, "col": 0, "role": "time"},
        {"key": "labels", "row": 2, "col": 0, "role": "labels"},
    ],
}


# ---------------- PLOT FUNCTION ---------------------------- [GEN]
def _clear_panel(ax):                                      # [GEN]
    """Drop the data artists WITHOUT calling ax.clear().

    The labeler has already run ax.clear(), xaxis_date() and
    set_xlim(t0, t1) before it calls plot_fn.  Calling clear() again
    here throws away the shared-axis links and the datetime unit
    converter it just installed, and the labeler's set_xlim then reaches
    only one axis -- the others keep a ~50-year auto-fit range and draw
    their line invisibly.  Removing artists is the safe half.
    """
    for artist in (list(ax.lines) + list(ax.collections)
                   + list(ax.patches) + list(ax.texts)):
        artist.remove()


def _have(ax, df, *columns):                               # [GEN]
    """The wizard generator's own guards, in source form.

    chronotagger.labeler.utils.plot_generator.generate_plot_fn draws a
    red "Column not found" notice on a panel it cannot draw and moves on
    to the next one, rather than raising.  This driver does the same, so
    editing load_dataframe() or the [YOURS] hook below -- dropping a
    column, renaming one, filtering every row away -- costs you ONE
    panel and a visible message, not the whole figure.
    """
    if len(df.index) == 0:
        ax.text(0.5, 0.5, "No data in window", ha="center", va="center",
                transform=ax.transAxes, color="gray")
        return False
    for column in columns:
        if column not in df.columns:
            ax.text(0.5, 0.5, "Error: Column '%s' not found" % column,
                    ha="center", va="center", transform=ax.transAxes,
                    color="red")
            return False
    return True


def plot_fn(axs, df, t0, t1):
    # [GEN] panel_1: BX
    ax = axs["panel_1"]
    _clear_panel(ax)
    if _have(ax, df, "BX"):
        ax.plot(df.index, df["BX"], color="#1f77b4", linewidth=1.0)
        ax.set_ylabel("BX", fontsize=9)
        ax.grid(alpha=0.3, linewidth=0.5)

    # [GEN] panel_2: n_linear
    ax = axs["panel_2"]
    _clear_panel(ax)
    if _have(ax, df, "n_linear"):
        ax.plot(df.index, df["n_linear"], color="#1f77b4", linewidth=1.0)
        ax.set_ylabel("n_linear", fontsize=9)
        ax.grid(alpha=0.3, linewidth=0.5)

    # ------------- YOUR ADDITIONS ------------------------- [YOURS]
    # Anything you draw here is a VISUAL AID: it renders, but box
    # selection never picks it up, because selection reads the dataframe
    # (or the data artists the blocks above drew), not your annotations.
    # Reference lines, model boundaries, extra traces and shaded bands
    # all belong here.  Example:
    #
    #     from geospacefronts import shue_mp
    #     x_mp, y_mp = shue_mp(...)
    #     axs["panel_1"].plot(x_mp, y_mp, "k--", lw=1)
    # ------------------------------------------------------------


# ---------------- LAUNCH ----------------------------------- [GEN]
AUTOSAVE_FOLDER = r".\\ct_autosave"
SOURCE_NAME = "peif"


if __name__ == "__main__":
    df = load_dataframe()

    # ------------- YOUR PRE-LAUNCH HOOK ------------------- [YOURS]
    # Filter to one spacecraft, subset a time range, derive
    # preloaded intervals from a label column -- anything that
    # shapes the frame the labeler sees.  Read the autosave
    # warning at the top of this file before you change which
    # rows or columns survive.  Example:
    #
    #     df = df[df["probe"] == 0].drop(columns=["probe"])
    # ------------------------------------------------------------

    app = TimeIntervalLabeler(
        df=df,
        plot_fn=plot_fn,
        layout_spec=LAYOUT,
        classes=CLASSES,
        class_colors=COLORS,
        window=pd.Timedelta("30min"),
        step=pd.Timedelta("15min"),
        autosave_folder=AUTOSAVE_FOLDER,
        source_name=SOURCE_NAME,
        decimate=True,
    )
    app.run()
'''


def _stack_csv_driver():
    return generate_driver(
        vertical_stack_config(["BX", "n_linear"]),
        data_path=r"C:\data\peif.csv",
        fmt="csv",
        time_column="time",
        autosave_folder=r".\ct_autosave",
        file_name="drive_peif.py",
    )


def test_golden_two_panel_vertical_stack_over_csv():
    """The whole emitted file, for the simplest real wizard answer.

    This is the one test that would notice a stray change anywhere in
    the template -- section order, [GEN]/[YOURS] markers, the
    constructor kwargs, the autosave warning, the _clear_panel and
    _have helpers and the guard indentation.  If it fails and the new
    text is what you meant, update the constant.
    """
    assert _norm(_stack_csv_driver()) == _norm(GOLDEN_STACK_CSV)


def test_emission_is_deterministic():
    assert _stack_csv_driver() == _stack_csv_driver()


def test_generated_source_is_valid_python():
    compile(_stack_csv_driver(), "<driver>", "exec")
    compile(_cross_driver(), "<driver>", "exec")


def test_generated_source_is_pure_ascii():
    """Cp1252 consoles are the reason this package is ASCII-only, and a
    column name is user data: a Greek mu in a header must not put a
    non-ASCII byte in the emitted file."""
    text = generate_driver(
        vertical_stack_config(["B_perp", "n_e"]),
        data_path="/data/x.csv", fmt="csv", time_column="epoch",
        autosave_folder="./out")
    assert text.isascii()

    exotic = generate_driver(
        vertical_stack_config(["B\u00b5", "n\u03bc"]),
        data_path="/data/x.csv", fmt="csv", time_column="epoch",
        autosave_folder="./out")
    assert exotic.isascii()

    # ...and the escaped literals still name the real columns: run the
    # emitted plot_fn against a frame that HAS them.  A vacuous
    # substring check would pass on an emitter that dropped the column
    # entirely (Pack 6 recheck FINDING 3, the same trap).
    from matplotlib.figure import Figure

    ns: dict = {}
    exec(compile(exotic.split('if __name__')[0], "<driver>", "exec"), ns)
    idx = pd.date_range("2021-01-01", periods=5, freq="1min")
    frame = pd.DataFrame({"B\u00b5": np.arange(5.0),
                          "n\u03bc": np.arange(5.0)}, index=idx)
    fig = Figure()
    axs = {"panel_1": fig.add_subplot(2, 1, 1),
           "panel_2": fig.add_subplot(2, 1, 2)}
    ns["plot_fn"](axs, frame, idx[0], idx[-1])
    assert len(axs["panel_1"].lines) == 1
    assert axs["panel_1"].get_ylabel() == "B\u00b5"


def test_a_non_ascii_timedelta_unit_still_returns_ascii_text():
    """v2 / V1 MINOR-1.  `_timedelta_lit` used to interpolate the
    caller's string straight into `pd.Timedelta("%s")`, so a MICRO SIGN
    -- a unit pandas accepts -- came back in the RETURN VALUE and only
    write_driver's ascii encoder caught it.  A Pack 8 caller writing the
    text through its own utf-8 handle would have shipped it."""
    micro = "1\u00b5s"
    assert pd.Timedelta(micro) == pd.Timedelta("1us")

    text = generate_driver(
        vertical_stack_config(["BX"]),
        data_path="/d/x.csv", fmt="csv", time_column="t",
        autosave_folder="./out", window=micro, step=micro)
    assert text.isascii()
    assert "pd.Timedelta('1\\xb5s')" in text

    # ...and the escape still parses back to the same duration.
    ns: dict = {}
    exec("import pandas as pd\nw = pd.Timedelta('1\\xb5s')", ns)
    assert ns["w"] == pd.Timedelta("1us")


# =====================================================================
# 2 -- exact-line goldens for the varying pieces
# =====================================================================

def test_csv_data_section_reads_csv_and_builds_the_index():
    lines = _norm(_stack_csv_driver()).split("\n")
    assert "    df = pd.read_csv(DATA_PATH)" in lines
    assert "    df.index = pd.to_datetime(df[TIME_COLUMN])" in lines
    assert '    df.index.name = "time"' in lines
    assert "    df = df.drop(columns=[TIME_COLUMN]).sort_index()" in lines
    assert "    df = pd.read_parquet(DATA_PATH)" not in lines


def test_parquet_data_section_reads_parquet():
    lines = _norm(_cross_driver()).split("\n")
    assert "    df = pd.read_parquet(DATA_PATH)" in lines
    assert "    df = pd.read_csv(DATA_PATH)" not in lines


def test_parquet_without_a_time_column_requires_a_datetimeindex():
    text = generate_driver(
        vertical_stack_config(["BX"]),
        data_path="/d/x.parquet", fmt="parquet", time_column=None,
        autosave_folder="./out")
    assert "TIME_COLUMN" not in text
    assert "if not isinstance(df.index, pd.DatetimeIndex):" in text
    assert "    return df.sort_index()" in _norm(text).split("\n")


def test_csv_without_a_time_column_is_refused():
    """pd.read_csv gives a RangeIndex; there is nothing to fall back on,
    so this must fail in the emitter rather than in the user's run."""
    with pytest.raises(ValueError, match="time_column"):
        generate_driver(vertical_stack_config(["BX"]),
                        data_path="/d/x.csv", fmt="csv", time_column=None,
                        autosave_folder="./out")


def test_cross_plot_layout_carries_x_col_and_y_col():
    """W2 at the emitter end: whatever the layout carries reaches the
    generated LAYOUT verbatim, in a readable fixed key order."""
    line = ('        {"key": "panel_3", "row": 0, "col": 1, "rowspan": 2, '
            '"role": "not-time", "x_col": "X", "y_col": "Y"},')
    assert line in _norm(_cross_driver()).split("\n")


def test_log_scale_panel_emits_set_yscale():
    lines = _norm(_cross_driver()).split("\n")
    assert '        ax.set_yscale("log")' in lines
    # exactly one panel asked for it
    assert lines.count('        ax.set_yscale("log")') == 1


def test_cross_plot_block_scatters_and_sets_equal_aspect():
    lines = _norm(_cross_driver()).split("\n")
    assert '    ax = axs["panel_3"]' in lines
    assert ('        ax.scatter(df["X"], df["Y"], s=5, c="#2ca02c", '
            'alpha=0.6)' in lines)
    assert '        ax.set_aspect("equal", adjustable="box")' in lines


def test_the_labels_area_gets_no_plot_block():
    """The defect that made the old emitter's output crash: a labels
    entry in plot_config produced `ax = axs['labels']`, and the labeler
    holds that strip outside `axs`."""
    text = _cross_driver()
    assert 'axs["labels"]' not in text
    assert "axs['labels']" not in text
    assert "labels" in text  # ...it is still in LAYOUT, where it belongs


def test_no_ax_clear_anywhere():
    """generate_plot_fn is documented at length on why it must not call
    ax.clear(); the emitted twin inherits that, and says so.

    Checked on the AST, not with a substring: the generated file
    deliberately NAMES ax.clear() in a comment and a docstring to
    explain why it does not call it, and a text scan would fail on the
    explanation instead of on a real call.
    """
    import ast

    text = _cross_driver()
    calls = [
        node for node in ast.walk(ast.parse(text))
        if isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr == "clear"
    ]
    assert calls == []
    assert "_clear_panel(ax)" in text


def test_scatter_style_and_colour_pass_through():
    layout = {"nrows": 2, "ncols": 1, "areas": [
        {"key": "p1", "row": 0, "col": 0, "role": "time"},
        {"key": "labels", "row": 1, "col": 0, "role": "labels"}]}
    cfg = {"p1": {"role": "time", "y_column": "BX", "style": "scatter",
                  "color": "#ff0000", "ylabel": "B [nT]", "grid": False,
                  "title": "field"}}
    text = generate_driver((layout, cfg), data_path="/d/x.csv", fmt="csv",
                           time_column="t", autosave_folder="./out")
    lines = _norm(text).split("\n")
    assert ('        ax.scatter(df.index, df["BX"], s=3, c="#ff0000", '
            'alpha=0.7)' in lines)
    assert '        ax.set_ylabel("B [nT]", fontsize=9)' in lines
    assert '        ax.set_title("field", fontsize=10)' in lines
    assert "        ax.grid(alpha=0.3, linewidth=0.5)" not in lines


# =====================================================================
# 3 -- CONTRACT
# =====================================================================

@pytest.mark.parametrize("folder", ["", ".", "./", ".\\", "  .  "])
def test_a_bare_cwd_autosave_folder_is_refused(folder):
    """The constructor's default is '.', which drops a fingerprinted
    autosave and a log file into whatever directory the driver happened
    to be launched from.  A GENERATED driver always names a folder."""
    with pytest.raises(ValueError, match="autosave_folder"):
        generate_driver(vertical_stack_config(["BX"]),
                        data_path="/d/x.csv", fmt="csv", time_column="t",
                        autosave_folder=folder)


@pytest.mark.parametrize("folder", ["./.", ".//", ".\\.", "./x/..",
                                    "  ./  ", ".\\out\\..", "a\\b/.."])
def test_other_spellings_of_the_cwd_are_refused_too(folder):
    """v2 / V1 MINOR-2.  The refusal used to be membership in a literal
    set, so the pin above was coextensive with the implementation and
    could not discover a leak.  These seven all resolve to exactly the
    process CWD under at least one path flavour, and none of them is in
    that set -- a normpath is what closes them.

    WHICH normpath is not a detail.  `os.path` alone leaves the backslash
    spellings open on POSIX (a backslash is an ordinary filename
    character there) and leaves `a\\b/..` open on Windows (nt reads it as
    the folder `a`), so a suite written against `os.path` passes on the
    machine that wrote it and fails on the other one -- measured, five
    reds on ubuntu CI.  A driver file is portable text, so the emitter
    refuses a spelling that is the CWD under EITHER rulebook and this
    parametrization is identical on every platform."""
    import ntpath
    import posixpath

    stripped = folder.strip()
    assert (posixpath.normpath(stripped) == "."
            or ntpath.normpath(stripped) == ".")
    with pytest.raises(ValueError, match="autosave_folder"):
        generate_driver(vertical_stack_config(["BX"]),
                        data_path="/d/x.csv", fmt="csv", time_column="t",
                        autosave_folder=folder)


@pytest.mark.parametrize("folder", ["./chronotagger_autosave", "..",
                                    "out", "/tmp/ct", "./a/b"])
def test_a_real_folder_is_accepted(folder):
    """The paired half: the guard must not swallow ordinary relative
    folders.  `..` is a DIFFERENT directory, not the CWD, so it passes."""
    text = generate_driver(vertical_stack_config(["BX"]),
                           data_path="/d/x.csv", fmt="csv", time_column="t",
                           autosave_folder=folder)
    assert "AUTOSAVE_FOLDER" in text


def test_an_unknown_format_is_refused():
    with pytest.raises(ValueError, match="fmt"):
        generate_driver(vertical_stack_config(["BX"]),
                        data_path="/d/x.feather", fmt="feather",
                        time_column="t", autosave_folder="./out")


def test_a_layout_with_only_a_labels_area_is_refused():
    layout = {"nrows": 1, "ncols": 1, "areas": [
        {"key": "labels", "row": 0, "col": 0, "role": "labels"}]}
    with pytest.raises(ValueError, match="drawable"):
        generate_driver((layout, {}), data_path="/d/x.csv", fmt="csv",
                        time_column="t", autosave_folder="./out")


def test_config_accepts_both_shapes_the_package_hands_around():
    pair = vertical_stack_config(["BX"])
    as_tuple = generate_driver(pair, data_path="/d/x.csv", fmt="csv",
                               time_column="t", autosave_folder="./out")
    as_mapping = generate_driver(
        {"layout_spec": pair[0], "plot_config": pair[1]},
        data_path="/d/x.csv", fmt="csv", time_column="t",
        autosave_folder="./out")
    assert as_tuple == as_mapping


@pytest.mark.parametrize("data_path", [r"E:\a\peif_with_labels.parquet",
                                      "E:/a/peif_with_labels.parquet",
                                      "/data/a/peif_with_labels.parquet"])
def test_source_name_defaults_to_the_data_file_stem(data_path):
    """Both separators are separators, on both platforms.

    `Path(...).stem` takes the flavour of the machine running the
    emitter, so on POSIX the Windows spelling has no separator to split
    on and the WHOLE PATH becomes the identity:
    SOURCE_NAME = 'E:\\a\\peif_with_labels' -- measured, and the same
    defect is what turned the full-file golden red."""
    text = generate_driver(vertical_stack_config(["BX"]),
                           data_path=data_path,
                           fmt="parquet", time_column="t",
                           autosave_folder="./out")
    assert 'SOURCE_NAME = "peif_with_labels"' in text


def test_a_drive_relative_data_path_still_reads_as_the_file_stem():
    """FOLD-1: the pin for EDIT 292's `ntpath.splitdrive`.

    `C:x.csv` is DRIVE-RELATIVE -- "x.csv in the current directory of
    drive C" -- and it is the one spelling that tells EDIT 292's two
    tokens apart.  `splitdrive` is what strips the `C:`; without it
    `PurePosixPath("C:x.csv").stem` is `C:x`, on BOTH platforms, and the
    claim that the stem fix is a ONE-WAY POSIX correction stops being
    true -- Windows answered `x` here at 9ad8770 and has to keep
    answering `x`.

    Every other pin in this file is blind to that token: the adversarial
    verifier dropped `splitdrive` and all 472 tests stayed green on
    Windows AND on the Dell.  This one is red on both platforms without
    it, which is the whole reason it exists.

    It is a test of its own rather than a fourth param of the sibling
    above because its expected stem differs; folding it in would have
    forced (path, expected) pairs and renamed three ids."""
    text = generate_driver(vertical_stack_config(["BX"]),
                           data_path="C:x.csv", fmt="parquet",
                           time_column="t", autosave_folder="./out")
    assert 'SOURCE_NAME = "x"' in text


def test_window_and_step_round_trip_through_pandas():
    from_str = generate_driver(vertical_stack_config(["BX"]),
                               data_path="/d/x.csv", fmt="csv",
                               time_column="t", autosave_folder="./out",
                               window="45min", step="5min")
    assert 'window=pd.Timedelta("45min"),' in from_str
    assert 'step=pd.Timedelta("5min"),' in from_str

    from_td = generate_driver(vertical_stack_config(["BX"]),
                              data_path="/d/x.csv", fmt="csv",
                              time_column="t", autosave_folder="./out",
                              window=pd.Timedelta("45min"),
                              step=pd.Timedelta("5min"))
    assert 'window=pd.Timedelta("0 days 00:45:00"),' in from_td
    ns: dict = {}
    exec("import pandas as pd\nw = pd.Timedelta(\"0 days 00:45:00\")", ns)
    assert ns["w"] == pd.Timedelta("45min")


def test_decimate_false_is_emitted():
    text = generate_driver(vertical_stack_config(["BX"]),
                           data_path="/d/x.csv", fmt="csv", time_column="t",
                           autosave_folder="./out", decimate=False)
    assert "decimate=False," in text


def test_regeneration_writes_a_complete_fresh_file(tmp_path):
    """W11: no merge machinery.  A hand edit inside a [YOURS] block is
    NOT preserved -- the file is rewritten whole -- and the generated
    header says so in as many words."""
    path = tmp_path / "drive.py"
    write_driver(_stack_csv_driver(), path)
    edited = path.read_text(encoding="ascii").replace(
        "    # ------------------------------------------------------------",
        "    print('my own hook')", 1)
    path.write_text(edited, encoding="ascii")
    assert "my own hook" in path.read_text(encoding="ascii")

    write_driver(_stack_csv_driver(), path)
    assert "my own hook" not in path.read_text(encoding="ascii")
    assert "NO merge-on-regenerate" in path.read_text(encoding="ascii")


def test_write_driver_normalises_line_endings(tmp_path):
    path = tmp_path / "sub" / "drive.py"           # parent does not exist
    mixed = "a = 1\r\nb = 2\nc = 3\r\n"
    write_driver(mixed, path)
    raw = path.read_bytes()
    assert raw == b"a = 1\r\nb = 2\r\nc = 3\r\n"

    write_driver(mixed, path, newline="\n")
    assert path.read_bytes() == b"a = 1\nb = 2\nc = 3\n"


def test_write_driver_refuses_non_ascii_text(tmp_path):
    with pytest.raises(UnicodeEncodeError):
        write_driver("x = \"\u00b5\"\n", tmp_path / "d.py")


def test_the_emitter_opens_no_dialogs():
    """The engine half is head-less by construction (W11): the wizard
    owns every file-choosing affordance, so this module must not so much
    as import a dialog."""
    from chronotagger.quickstart import driver_export

    src = Path(driver_export.__file__).read_text(encoding="utf-8")
    for needle in ("filedialog", "messagebox", "tkinter", "import tk"):
        assert needle not in src


# ---------------------------------------------------------------------
# v2 / V1 MAJOR-2 -- plain literals only
# ---------------------------------------------------------------------

def test_numpy_scalars_in_a_layout_become_plain_literals():
    """A layout built from np.arange or DataFrame.shape is the normal
    idiom for this user base.  Under numpy 2 `repr(np.int64(3))` is
    `'np.int64(3)'` -- valid Python naming a module the driver never
    imports, so the file COMPILES and dies on import with NameError.
    """
    layout = {
        "nrows": np.int64(2), "ncols": np.int64(1),
        "hspace": np.float64(0.15),
        "areas": [
            {"key": "p1", "row": np.int64(0), "col": np.int64(0),
             "rowspan": np.int64(1), "role": "time"},
            {"key": "labels", "row": np.int64(1), "col": np.int64(0),
             "role": "labels"},
        ],
    }
    cfg = {"p1": {"role": "time", "y_column": np.str_("BX")}}
    text = generate_driver((layout, cfg), data_path="/d/x.csv", fmt="csv",
                           time_column="t", autosave_folder="./out")

    assert "np." not in text
    assert '"nrows": 2,' in text
    assert '"hspace": 0.15,' in text
    assert ('        {"key": "p1", "row": 0, "col": 0, "rowspan": 1, '
            '"role": "time"},') in _norm(text).split("\n")
    assert 'df["BX"]' in text

    # ...and the module-level half really EXECUTES, which is the failure
    # a compile() check cannot see.
    ns: dict = {}
    exec(compile(text.split("if __name__")[0], "<driver>", "exec"), ns)
    assert ns["LAYOUT"]["nrows"] == 2
    assert isinstance(ns["LAYOUT"]["nrows"], int)


def test_numpy_scalars_in_the_label_schema_become_plain_literals():
    text = generate_driver(
        vertical_stack_config(["BX"]),
        data_path="/d/x.csv", fmt="csv", time_column="t",
        autosave_folder="./out",
        classes=[np.str_("sheet"), np.str_("lobe")],
        colors={np.str_("sheet"): np.str_("#d62728"),
                np.str_("lobe"): np.str_("#1f77b4")},
        decimate=np.bool_(False))
    assert "np." not in text
    assert 'CLASSES = ["sheet", "lobe"]' in text
    assert '    "sheet": "#d62728",' in text
    assert "decimate=False," in text
    ns: dict = {}
    exec(compile(text.split("if __name__")[0], "<driver>", "exec"), ns)
    assert ns["CLASSES"] == ["sheet", "lobe"]


def test_pandas_scalars_become_plain_literals():
    layout = {"nrows": 2, "ncols": 1, "areas": [
        {"key": "p1", "row": 0, "col": 0, "role": "time",
         "note": pd.Timestamp("2021-03-01")},
        {"key": "labels", "row": 1, "col": 0, "role": "labels"}]}
    cfg = {"p1": {"role": "time", "y_column": "BX"}}
    text = generate_driver((layout, cfg), data_path="/d/x.csv", fmt="csv",
                           time_column="t", autosave_folder="./out")
    assert "Timestamp(" not in text
    assert '"note": "2021-03-01T00:00:00"' in text


def test_a_value_with_no_plain_literal_form_is_refused():
    """The doctrine everywhere else in this module: refuse at emission
    rather than emit something that dies later."""
    layout = {"nrows": 2, "ncols": 1, "areas": [
        {"key": "p1", "row": 0, "col": 0, "role": "time",
         "note": object()},
        {"key": "labels", "row": 1, "col": 0, "role": "labels"}]}
    cfg = {"p1": {"role": "time", "y_column": "BX"}}
    with pytest.raises(ValueError, match="literal"):
        generate_driver((layout, cfg), data_path="/d/x.csv", fmt="csv",
                        time_column="t", autosave_folder="./out")


# ---------------------------------------------------------------------
# v2 / V1 MAJOR-3 + V2 F-V2-05 / F-V2-07 -- B's guards, in source form
# ---------------------------------------------------------------------

def test_a_panel_with_no_column_is_refused_at_emission():
    """F-V2-05.  A drawable area with no matching plot_config entry used
    to emit `ax.plot(df.index, df[None], ...)` -- compiles, KeyError on
    the first render.  That is the same defect class this pack exists to
    kill (the old ramp's axs['labels'])."""
    layout = {"nrows": 2, "ncols": 1, "areas": [
        {"key": "p1", "row": 0, "col": 0, "role": "time"},
        {"key": "labels", "row": 1, "col": 0, "role": "labels"}]}
    with pytest.raises(ValueError, match="no y_column"):
        generate_driver((layout, {}), data_path="/d/x.csv", fmt="csv",
                        time_column="t", autosave_folder="./out")

    cross = {"nrows": 2, "ncols": 1, "areas": [
        {"key": "p1", "row": 0, "col": 0, "role": "not-time"},
        {"key": "labels", "row": 1, "col": 0, "role": "labels"}]}
    with pytest.raises(ValueError, match="x_column or y_column"):
        generate_driver((cross, {"p1": {"role": "not-time"}}),
                        data_path="/d/x.csv", fmt="csv", time_column="t",
                        autosave_folder="./out")

    assert "df[None]" not in _cross_driver()


def test_the_emitted_plot_fn_carries_the_runtime_missing_column_guard():
    """MAJOR-3.  The [YOURS] pre-launch hook literally demonstrates
    `df.drop(columns=["probe"])`.  A user who drops or renames a PLOTTED
    column must lose one panel and see why, exactly as the wizard's live
    figure does -- not lose the whole figure to a KeyError."""
    from matplotlib.figure import Figure

    from chronotagger.labeler.utils import generate_plot_fn

    layout, cfg = vertical_stack_config(["BX", "n_linear"])
    text = generate_driver((layout, cfg), data_path="/d/x.csv", fmt="csv",
                           time_column="t", autosave_folder="./out")
    ns: dict = {}
    exec(compile(text.split("if __name__")[0], "<driver>", "exec"), ns)

    idx = pd.date_range("2021-03-01", periods=10, freq="1min")
    # n_linear was dropped by the user's own hook; BX survives.
    df = pd.DataFrame({"BX": np.arange(10.0)}, index=idx)

    fig = Figure()
    axs = {"panel_1": fig.add_subplot(2, 1, 1),
           "panel_2": fig.add_subplot(2, 1, 2)}
    ns["plot_fn"](axs, df, idx[0], idx[-1])          # must NOT raise

    assert len(axs["panel_1"].lines) == 1            # the survivor drew
    assert len(axs["panel_2"].lines) == 0            # the casualty did not
    assert [t.get_text() for t in axs["panel_2"].texts] == [
        "Error: Column 'n_linear' not found"]

    # ...and that is byte-for-byte the RUNTIME generator's message.
    fig2 = Figure()
    axs2 = {"panel_1": fig2.add_subplot(2, 1, 1),
            "panel_2": fig2.add_subplot(2, 1, 2)}
    generate_plot_fn(cfg)(axs2, df, idx[0], idx[-1])
    assert [t.get_text() for t in axs2["panel_2"].texts] == [
        t.get_text() for t in axs["panel_2"].texts]


def test_the_emitted_plot_fn_carries_the_empty_window_guard():
    from matplotlib.figure import Figure

    layout, cfg = vertical_stack_config(["BX"])
    text = generate_driver((layout, cfg), data_path="/d/x.csv", fmt="csv",
                           time_column="t", autosave_folder="./out")
    ns: dict = {}
    exec(compile(text.split("if __name__")[0], "<driver>", "exec"), ns)

    empty = pd.DataFrame({"BX": []},
                         index=pd.DatetimeIndex([], name="time"))
    fig = Figure()
    ax = fig.add_subplot(1, 1, 1)
    ns["plot_fn"]({"panel_1": ax}, empty, None, None)
    assert [t.get_text() for t in ax.texts] == ["No data in window"]


def test_a_role_the_runtime_generator_never_draws_emits_nothing():
    """F-V2-07.  B dispatches `if time ... elif not-time` and draws
    nothing otherwise; the emitter used to fall into its cross-plot
    branch, inventing a scatter B would never render."""
    layout = {"nrows": 3, "ncols": 1, "areas": [
        {"key": "p1", "row": 0, "col": 0, "role": "time"},
        {"key": "spectro", "row": 1, "col": 0, "role": "spectrogram"},
        {"key": "labels", "row": 2, "col": 0, "role": "labels"}]}
    cfg = {"p1": {"role": "time", "y_column": "BX"},
           "spectro": {"role": "spectrogram", "y_column": "eflux"}}
    text = generate_driver((layout, cfg), data_path="/d/x.csv", fmt="csv",
                           time_column="t", autosave_folder="./out")
    assert 'axs["spectro"]' not in text
    assert 'axs["p1"]' in text
    # ...it is still in LAYOUT, so the labeler still builds the axes.
    assert '"key": "spectro"' in text


# ---------------------------------------------------------------------
# v2 / V1 MINOR-3 -- the multi-pane refusal names its cause
# ---------------------------------------------------------------------

def test_a_multi_pane_session_is_refused_by_name():
    """EDIT 277 hands a Pack 8 implementer `wizard.pane_specs`, a LIST.
    A two-element list used to unpack as (layout_spec, plot_config) and
    die claiming the first pane had no 'areas' -- a misleading error at
    exactly the seam where multi-pane is parked."""
    layout, cfg = vertical_stack_config(["BX"])
    panes = [{"title": "Fields", "layout_spec": layout, "plot_config": cfg},
             {"title": "Position", "layout_spec": layout, "plot_config": cfg}]

    for shape in (panes, tuple(panes), panes + panes[:1]):
        with pytest.raises(ValueError) as exc:
            generate_driver(shape, data_path="/d/x.csv", fmt="csv",
                            time_column="t", autosave_folder="./out")
        message = str(exc.value)
        assert "multi-pane" in message
        assert "Pack 8" in message
        assert "%d panes" % len(shape) in message
        assert "pane_specs[0]" in message
        assert "areas" not in message

    # ...and one pane out of that same list still works.
    text = generate_driver(panes[0], data_path="/d/x.csv", fmt="csv",
                           time_column="t", autosave_folder="./out")
    assert 'axs["panel_1"]' in text


# ---------------------------------------------------------------------
# v2 / V1 MAJOR-1 -- the time-unit contract
# ---------------------------------------------------------------------

def test_an_epoch_column_must_name_its_unit():
    """The whole point.  pd.to_datetime reads a bare integer column as
    NANOSECONDS, so an unlabelled microsecond epoch relocates the
    dataset to 1970 AND still produces a valid DatetimeIndex."""
    with pytest.raises(ValueError, match="time_unit"):
        generate_driver(vertical_stack_config(["BX"]),
                        data_path="/d/x.parquet", fmt="parquet",
                        time_column="t_ns", time_is_epoch=True,
                        autosave_folder="./out")


def test_a_unit_without_an_epoch_column_is_refused():
    """The paired half: a unit means nothing for a column of date
    strings, and accepting it silently would let a caller believe they
    had said something about the conversion."""
    with pytest.raises(ValueError, match="time_is_epoch"):
        generate_driver(vertical_stack_config(["BX"]),
                        data_path="/d/x.csv", fmt="csv", time_column="t",
                        time_unit="us", autosave_folder="./out")


def test_an_unknown_epoch_unit_is_refused():
    with pytest.raises(ValueError, match="time_unit must be one of"):
        generate_driver(vertical_stack_config(["BX"]),
                        data_path="/d/x.parquet", fmt="parquet",
                        time_column="t", time_is_epoch=True,
                        time_unit="fortnights", autosave_folder="./out")


@pytest.mark.parametrize("unit", ["s", "ms", "us", "ns"])
def test_an_epoch_driver_emits_the_unit_it_was_given(unit):
    text = generate_driver(
        vertical_stack_config(["BX"]),
        data_path="/d/x.parquet", fmt="parquet", time_column="t",
        time_is_epoch=True, time_unit=unit, autosave_folder="./out")
    lines = _norm(text).split("\n")
    assert 'TIME_UNIT = "%s"' % unit in lines
    assert ("    df.index = pd.to_datetime(df[TIME_COLUMN], unit=TIME_UNIT)"
            in lines)
    assert "    df.index = pd.to_datetime(df[TIME_COLUMN])" not in lines


def test_a_datetime_column_driver_emits_the_bare_call():
    lines = _norm(_stack_csv_driver()).split("\n")
    assert "    df.index = pd.to_datetime(df[TIME_COLUMN])" in lines
    assert "TIME_UNIT" not in _stack_csv_driver()


# =====================================================================
# 4 -- EXECUTION SMOKE: write it, run it in a subprocess, construct
# =====================================================================

_RUNNER = '''\
"""Head-less runner for a generated driver.

Stubs tkinter.messagebox and tkinter.filedialog FIRST, forces Agg, then
neutralises TimeIntervalLabeler.run so the driver's __main__ guard can
construct the app without entering a Tk mainloop.  Prints one JSON line.
"""
import sys
import types

import tkinter

_mb = types.ModuleType("tkinter.messagebox")
for _n in ("showerror", "showwarning", "showinfo"):
    setattr(_mb, _n, lambda *a, **k: "ok")
for _n in ("askyesno", "askokcancel", "askyesnocancel"):
    setattr(_mb, _n, lambda *a, **k: True)
sys.modules["tkinter.messagebox"] = _mb
tkinter.messagebox = _mb

_fd = types.ModuleType("tkinter.filedialog")
for _n in ("askopenfilename", "asksaveasfilename", "askdirectory"):
    setattr(_fd, _n, lambda *a, **k: "")
sys.modules["tkinter.filedialog"] = _fd
tkinter.filedialog = _fd

import matplotlib
matplotlib.use("Agg")
from matplotlib.figure import Figure

import json
import runpy

import pandas as pd

from chronotagger.labeler import TimeIntervalLabeler

_captured = {}


def _fake_run(self):
    _captured["app"] = self


TimeIntervalLabeler.run = _fake_run

ns = runpy.run_path(sys.argv[1], run_name="__main__")
app = _captured["app"]

# Exercise the emitted plot_fn against real axes -- twice, because a
# generator that accumulates artists is exactly the bug this replaced.
layout = ns["LAYOUT"]
fig = Figure(figsize=(6, 4))
axs = {}
for area in layout["areas"]:
    if area.get("role") != "labels":
        axs[area["key"]] = fig.add_subplot(len(axs) + 1, 1, len(axs) + 1)
for _ in range(2):
    ns["plot_fn"](axs, app.df, app.t0, app.t1)

print(json.dumps({
    "rows": int(len(app.df)),
    "panes": len(app.panes),
    "areas": len(layout["areas"]),
    "columns": list(map(str, app.df.columns)),
    "index_is_datetime": isinstance(app.df.index, pd.DatetimeIndex),
    "first": str(app.df.index[0]) if len(app.df.index) else None,
    "last": str(app.df.index[-1]) if len(app.df.index) else None,
    "classes": list(app.classes),
    "window": str(app.window),
    "step": str(app.step),
    "decimate": bool(app.decimate),
    "source_name": app.source_name,
    "autosave_folder": str(app.autosave_folder),
    "artists": {k: [len(a.lines), len(a.collections)] for k, a in axs.items()},
    "texts": {k: [t.get_text() for t in a.texts] for k, a in axs.items()},
}))
'''


def _sample_frame(n=240):
    idx = pd.date_range("2021-03-01", periods=n, freq="10s")
    return pd.DataFrame({
        "BX": np.sin(np.linspace(0, 8, n)),
        "n_linear": np.abs(np.sin(np.linspace(0, 2, n))) + 0.02,
        "X": np.linspace(-60.0, -20.0, n),
        "Y": np.linspace(-9.0, 9.0, n),
        "liuzzo_class": ["sheet"] * n,          # non-numeric: must survive
    }, index=idx)


def _epoch_column(index, unit):
    """A genuine integer epoch in `unit`, whatever pandas' own index
    resolution happens to be.

    Under pandas 3 `pd.date_range(...)` is `datetime64[us]`, so
    `index.view("int64")` is a MICROSECOND count -- which is exactly how
    v1's fixture came to be a microsecond epoch that its driver then
    read as nanoseconds.  Convert explicitly instead of viewing.
    """
    ns = index.astype("datetime64[ns]").astype("int64")
    divisor = {"ns": 1, "us": 1000, "ms": 1000000, "s": 1000000000}[unit]
    assert (ns % divisor == 0).all(), "fixture is not exact in %s" % unit
    return ns // divisor


def _run_driver(tmp_path, driver_text, name="drive.py"):
    driver = tmp_path / name
    write_driver(driver_text, driver)
    runner = tmp_path / "run_driver.py"
    runner.write_text(_RUNNER, encoding="ascii")

    env = dict(os.environ)
    env["PYTHONPATH"] = str(SRC_ROOT)
    env["MPLBACKEND"] = "Agg"
    proc = subprocess.run(
        [sys.executable, str(runner), str(driver)],
        capture_output=True, text=True, cwd=str(tmp_path), env=env)
    assert proc.returncode == 0, (
        "generated driver failed to run\n"
        "--- stdout ---\n%s\n--- stderr ---\n%s" % (proc.stdout, proc.stderr))
    return json.loads(proc.stdout.strip().splitlines()[-1])


def test_emitted_csv_driver_runs_and_constructs(tmp_path):
    frame = _sample_frame()
    data = tmp_path / "sample.csv"
    frame.reset_index(names="t").to_csv(data, index=False)

    text = generate_driver(
        vertical_stack_config(["BX", "n_linear"]),
        data_path=str(data), fmt="csv", time_column="t",
        classes=["sheet", "lobe"],
        colors={"sheet": "#d62728", "lobe": "#1f77b4"},
        window="10min", step="5min",
        autosave_folder=str(tmp_path / "autosave"),
        source_name="sample_csv", decimate=False)

    got = _run_driver(tmp_path, text, "drive_csv.py")
    assert got["rows"] == 240
    assert got["panes"] == 1
    assert got["areas"] == 3
    assert got["index_is_datetime"] is True
    assert "t" not in got["columns"]                  # became the index
    assert "liuzzo_class" in got["columns"]           # W4: ALL columns
    assert got["classes"] == ["sheet", "lobe"]
    assert got["window"] == "0 days 00:10:00"
    assert got["step"] == "0 days 00:05:00"
    assert got["decimate"] is False
    assert got["source_name"] == "sample_csv"
    assert got["artists"] == {"panel_1": [1, 0], "panel_2": [1, 0]}
    # the VALUES, not only the dtype
    assert got["first"] == "2021-03-01 00:00:00"
    assert got["last"] == "2021-03-01 00:39:50"


def test_emitted_parquet_driver_with_a_crossplot_runs_and_constructs(tmp_path):
    frame = _sample_frame()
    data = tmp_path / "sample.parquet"
    frame.assign(t_ns=_epoch_column(frame.index, "ns")).reset_index(
        drop=True).to_parquet(data)

    text = generate_driver(
        {"layout_spec": CROSS_LAYOUT, "plot_config": {
            "panel_1": {"role": "time", "y_column": "n_linear",
                        "yscale": "log"},
            "panel_2": {"role": "time", "y_column": "BX"},
            "labels": {"role": "labels", "x_column": None,
                       "y_column": None},
            "panel_3": {"role": "not-time", "x_column": "X",
                        "y_column": "Y", "equal_aspect": True}}},
        data_path=str(data), fmt="parquet", time_column="t_ns",
        time_is_epoch=True, time_unit="ns",
        window="10min", step="5min",
        autosave_folder=str(tmp_path / "autosave"),
        source_name="sample_parquet")

    got = _run_driver(tmp_path, text, "drive_parquet.py")
    assert got["rows"] == 240
    assert got["panes"] == 1
    assert got["areas"] == 4
    assert got["index_is_datetime"] is True
    assert "t_ns" not in got["columns"]
    assert "liuzzo_class" in got["columns"]
    # two line panels and one scatter panel, and NOTHING accumulated on
    # the second render pass
    assert got["artists"] == {"panel_1": [1, 0], "panel_2": [1, 0],
                              "panel_3": [0, 1]}
    assert got["first"] == "2021-03-01 00:00:00"
    assert got["last"] == "2021-03-01 00:39:50"


@pytest.mark.parametrize("unit", ["ns", "us"])
def test_an_epoch_driver_round_trips_the_ACTUAL_TIMESTAMPS(tmp_path, unit):
    """v2 / V1 MAJOR-1, the pin that replaces a dtype check.

    v1 asserted only `index_is_datetime`, which is True whether the
    conversion is right or 51 years wrong -- and v1's own parquet
    fixture WAS a microsecond epoch read as nanoseconds, so its
    "W4's conversion" evidence proved nothing. This runs the emitted
    driver in a subprocess and demands the exact timestamps back.
    """
    frame = _sample_frame()
    epoch = _epoch_column(frame.index, unit)
    assert epoch.dtype == np.int64
    if unit == "us":
        # the exact shape that fooled v1: a microsecond count read as
        # nanoseconds lands in 1970
        assert str(pd.to_datetime(epoch[0])).startswith("1970")

    data = tmp_path / ("sample_%s.parquet" % unit)
    frame.assign(t_epoch=epoch).reset_index(drop=True).to_parquet(data)

    text = generate_driver(
        vertical_stack_config(["BX", "n_linear"]),
        data_path=str(data), fmt="parquet", time_column="t_epoch",
        time_is_epoch=True, time_unit=unit,
        window="10min", step="5min",
        autosave_folder=str(tmp_path / ("autosave_%s" % unit)),
        source_name="epoch_%s" % unit)
    assert 'TIME_UNIT = "%s"' % unit in text

    got = _run_driver(tmp_path, text, "drive_%s.py" % unit)
    assert got["rows"] == 240
    assert got["index_is_datetime"] is True
    assert got["first"] == "2021-03-01 00:00:00"
    assert got["last"] == "2021-03-01 00:39:50"
    assert not got["first"].startswith("1970")


def test_an_emitted_driver_survives_a_YOURS_hook_that_drops_a_column(tmp_path):
    """MAJOR-3, end to end and in a subprocess.

    The generated [YOURS] pre-launch hook demonstrates a `df.drop`. Do
    exactly that to a PLOTTED column and the driver must still start,
    with one panel showing the runtime generator's own red notice.
    """
    frame = _sample_frame()
    data = tmp_path / "sample.csv"
    frame.reset_index(names="t").to_csv(data, index=False)

    text = generate_driver(
        vertical_stack_config(["BX", "n_linear"]),
        data_path=str(data), fmt="csv", time_column="t",
        window="10min", step="5min",
        autosave_folder=str(tmp_path / "autosave"),
        source_name="dropped")
    # play the user: drop a plotted column in the pre-launch hook
    hooked = text.replace(
        "    df = load_dataframe()\n",
        '    df = load_dataframe()\n    df = df.drop(columns=["n_linear"])\n',
        1)
    assert 'df.drop(columns=["n_linear"])' in hooked

    got = _run_driver(tmp_path, hooked, "drive_dropped.py")
    assert got["rows"] == 240
    assert "n_linear" not in got["columns"]
    # panel_1 still drew its line; panel_2 drew a notice instead
    assert got["artists"]["panel_1"] == [1, 0]
    assert got["artists"]["panel_2"] == [0, 0]
    assert got["texts"]["panel_2"] == ["Error: Column 'n_linear' not found"]
